version: '3.8'

services:
  spark-master:
    image: bitnamilegacy/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - .:/opt/bitnami/spark/work
    networks:
      - spark-network

  spark-worker:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - .:/opt/bitnami/spark/work
    networks:
      - spark-network
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - .:/opt/bitnami/spark/work
    networks:
      - spark-network
    depends_on:
      - spark-master

  spark-worker-3:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - .:/opt/bitnami/spark/work
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge
